apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-detector-core
spec:
  selector:
    matchLabels:
      app: car-detector-core
  template:
    metadata:
      labels:
        app: car-detector-core
    spec:
      containers:
        - name: car-detector-core
          image: akos0628/car-detector-core:{{ .Values.env.APP_VERSION }}
          env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{ - end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
