apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "pic"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "image"
            - name: MONGO_INITDB_DATABASE
              value: "pictureCatalog"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 16Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb